config_version = 14

[audio]
enable_overdrive = true

[bar.default]
background_opacity = 0.89999997988343239
capsule_radius = 8
center = [ "audio_visualizer", "clock" ]
end = [ "tray", "bluetooth", "network", "volume", "brightness", "battery" ]
font_family = "JetBrainsMono Nerd Font"
icon_color = "primary"
margin_ends = 0
padding = 16
radius = 8
radius_top_left = 0
radius_top_right = 0
start = [ "workspaces" ]
widget_spacing = 18

[brightness]
sync_all_monitors = true

[control_center]
show_shortcut_labels = false
sidebar = "none"
sidebar_section = "none"

    [control_center.calendar]
    show_events_card = false

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "keyboard_layout"

    [[control_center.shortcuts]]
    type = "power_profile"

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 224.0
    box_width = 512.0
    cx = 1280.0
    cy = 240.0
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        clock_style = "digital"
        color = "primary"
        font_family = ""
        format = "{:%-I:%M %p}"
        shadow = false

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 544.0
    box_width = 2608.0
    cx = 1280.0
    cy = 1344.0
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = -0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        bands = 64
        centered = false
        color_1 = "primary"
        color_2 = "primary"
        mirrored = false
        reversed = false
        show_when_idle = true

[dock]
auto_hide = true
background_opacity = 0.89999997988343239
enabled = true
radius = 8
reserve_space = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true
edge_smoothness = 0.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1308.800048828125
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.89999997988343239

[osd]
background_opacity = 0.89999997988343239

[plugins]
enabled = []

[shell]
corner_radius_scale = 0.5000000074505806
password_style = "random"
polkit_agent = true
screen_time_enabled = true
time_format = "{:%-I:%M %p}"

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    categories = false

    [shell.panel]
    borders = false
    control_center_placement = "floating"
    open_near_click_control_center = true
    session_placement = "floating"
    transparency_mode = "soft"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screenshot]
    directory = "/home/ziad/Pictures/screenshots"
    show_cursor = true

    [shell.session]
    show_shortcuts = false

[theme]
builtin = "Rosé Pine"
community_palette = "Aura"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "hyprland", "qt" ]
    community_ids = [ "zen-browser", "discord", "libreoffice", "zed", "prismlauncher", "obs", "papirus-icons" ]

[wallpaper]
directory = "/home/ziad/Pictures/wallpapers"
edge_smoothness = 0.0
transition_on_startup = true

    [wallpaper.default]
    path = "/home/ziad/Pictures/wallpapers/wallhaven-216k99_2560x1600.png"

    [wallpaper.last]
    path = "/home/ziad/Pictures/wallpapers/wallhaven-216k99_2560x1600.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/ziad/Pictures/wallpapers/wallhaven-216k99_2560x1600.png"

    [[wallpaper.favorite]]
    builtin_palette = "Rosé Pine"
    palette_source = "builtin"
    path = "/home/ziad/Pictures/wallpapers/wallhaven-3q6m6y_2560x1600.png"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    path = "/home/ziad/Pictures/wallpapers/wallhaven-5yp7j8_2560x1600.png"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/ziad/Pictures/wallpapers/wallhaven-xek51o_2560x1600.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/ziad/Pictures/wallpapers/wallhaven-yqkqeg_2560x1600.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

[widget.clock]
anchor = true
format = "{:%a %d %b %-I:%M %p}"