# 00-ignore.sh - Ignore noisy, generated, or cache files

# General runtime and cache directories
IgnorePath '*.log'
IgnorePath '*/log/*'
IgnorePath '*cache*'
IgnorePath '*history*'
IgnorePath '/boot/*'
IgnorePath '/var/*'
IgnorePath '/tmp/*'
IgnorePath '*/.snapshots*'
IgnorePath '/etc/.updated'

# Pacman backups and temporary files
IgnorePath '*.pacnew'
IgnorePath '*.pacsave'
IgnorePath '*.bak'
IgnorePath '*.old'

# Auto-generated MIME, Desktop, and Icon databases
IgnorePath '/usr/share/mime/*'
IgnorePath '/usr/share/icons/*'
IgnorePath '/usr/share/glib-2.0/schemas/gschemas.compiled'
IgnorePath '/usr/share/info/dir'

# Auto-generated Kernels & Modules
IgnorePath '/usr/lib/modules/*'

# Various binary caches and logs
IgnorePath '/usr/lib/locale/locale-archive'
IgnorePath '/usr/lib/udev/hwdb.bin'

# SSL Certificates and Keyrings (Auto-generated by ca-certificates)
IgnorePath '/etc/ca-certificates/extracted/*'
IgnorePath '/etc/ssl/certs/*'
IgnorePath '/etc/pacman.d/gnupg/*'

# Font configs (Auto-managed symlinks)
IgnorePath '/etc/fonts/conf.d/*'
